# Generated by Django 4.1.3 on 2022-12-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_client_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
